name: Publish to GitHub Packages (Docker)

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  # Menggunakan kombinasi username dan nama package yang baru
  IMAGE_NAME: ${{ github.repository_owner }}/cerberus-cli

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Izin khusus agar bisa upload ke tab Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          # Token ini sudah otomatis disediakan oleh GitHub, nggak perlu kamu buat manual
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
